trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: '**/pom.xml'
      goals: 'clean install'

  - task: Docker@2
    inputs:
      command: buildAndPush
      repository: 'product-service'
      dockerfile: 'Backend/product-service/Dockerfile'
      containerRegistry: '$(dockerRegistryServiceConnection)'
      tags: |
        $(Build.BuildId)
