apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ecommerceacr7.azurecr.io/product-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: product-service
#spec:
#  selector:
#    app: product-service
#  ports:
#    - port: 8081
#      targetPort: 8081

#-- Below is for releasing External Ip so that we can hit apis from outside
#apiVersion: v1
#kind: Service
#metadata:
#  name: product-service-svc
#spec:
#  type: LoadBalancer
#  selector:
#    app: product-service
#  ports:
#    - port: 8081
#      targetPort: 8081

